import { EventEmitter } from 'events'

class store extends EventEmitter {
	constructor() {
		super()
		this.data = {
			/*chinese: {
				requests: {
					buddies: {
						[]
					},
					events: {
						[]
					}
					life: {
						[]
					},
				},
				support: {
					buddies: {
						[]
					},
					events: {
						[]
					}
					life: {
						[]
					},
				},
				view: {
					navbar: {

					}
				},
			},*/
			english: {
				requests: {
					buddies: [
						{
							id: "b1i53i",
							title: "Please show me around Nagoya City！",
							category: "その他",
							host: "Ito Anna",
							date: "11/01/2017",
							price: "¥500/時",
							img: "https://i.imgur.com/anNQR3T.jpg",
							url: "/details/requests/buddies/b1i53i",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/anNQR3T.jpg",
							sec_img: "https://i.imgur.com/GIXcM8A.jpg",
							thr_img: "https://i.imgur.com/MqHaQUP.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "L4c10y",
							title: "保険の申し込み方",
							category: "生活相談",
							host: "渡辺愛莉",
							date: "11/02/2017",
							price: "¥1500/時",
							img: "https://i.imgur.com/v1JbZ3h.jpg",
							url: "/details/requests/buddies/L4c10y",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/v1JbZ3h.jpg",
							sec_img: "https://i.imgur.com/FeKfXsD.jpg",
							thr_img: "https://i.imgur.com/mZxKsxg.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "jW1h44",
							title: "引っ越し手伝い募集中",
							category: "交通",
							host: "高橋恵介",
							date: "11/03/2017",
							price: "¥2000/時",
							img: "https://i.imgur.com/wJGbDaM.jpg",
							url: "/details/requests/buddies/jW1h44",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/wJGbDaM.jpg",
							sec_img: "https://i.imgur.com/AP48h4L.jpg",
							thr_img: "https://i.imgur.com/vpOMwM9.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "T8kf21",
							title: "日本語でお話しませんか？",
							category: "生活相談",
							host: "鈴木美咲",
							date: "11/04/2017",
							price: "¥2500/時",
							img: "https://i.imgur.com/BBBfGcN.jpg",
							url: "/details/requests/buddies/T8kf21",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/BBBfGcN.jpg",
							sec_img: "https://i.imgur.com/VLRkgd9.jpg",
							thr_img: "https://i.imgur.com/KO2exIV.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
					],
					events: [
						{
							id: "b1i53i",
							title: "名古屋市内の案内お願いします！",
							category: "その他",
							host: "伊藤杏那",
							date: "11/01/2017",
							price: "¥500/時",
							img: "https://i.imgur.com/anNQR3T.jpg",
							url: "/details/requests/events/b1i53i",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/anNQR3T.jpg",
							sec_img: "https://i.imgur.com/GIXcM8A.jpg",
							thr_img: "https://i.imgur.com/MqHaQUP.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "L4c10y",
							title: "保険の申し込み方",
							category: "生活相談",
							host: "渡辺愛莉",
							date: "11/02/2017",
							price: "¥1500/時",
							img: "https://i.imgur.com/v1JbZ3h.jpg",
							url: "/details/requests/events/L4c10y",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/v1JbZ3h.jpg",
							sec_img: "https://i.imgur.com/FeKfXsD.jpg",
							thr_img: "https://i.imgur.com/mZxKsxg.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "jW1h44",
							title: "引っ越し手伝い募集中",
							category: "交通",
							host: "高橋恵介",
							date: "11/03/2017",
							price: "¥2000/時",
							img: "https://i.imgur.com/wJGbDaM.jpg",
							url: "/details/requests/events/jW1h44",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/wJGbDaM.jpg",
							sec_img: "https://i.imgur.com/AP48h4L.jpg",
							thr_img: "https://i.imgur.com/vpOMwM9.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "T8kf21",
							title: "日本語でお話しませんか？",
							category: "生活相談",
							host: "鈴木美咲",
							date: "11/04/2017",
							price: "¥2500/時",
							img: "https://i.imgur.com/BBBfGcN.jpg",
							url: "/details/requests/events/T8kf21",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/BBBfGcN.jpg",
							sec_img: "https://i.imgur.com/VLRkgd9.jpg",
							thr_img: "https://i.imgur.com/KO2exIV.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
					],
					life: [
						{
							id: "b1i53i",
							title: "名古屋市内の案内お願いします！",
							category: "その他",
							host: "伊藤杏那",
							date: "11/01/2017",
							price: "¥500/時",
							img: "https://i.imgur.com/anNQR3T.jpg",
							url: "/details/requests/life/b1i53i",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/anNQR3T.jpg",
							sec_img: "https://i.imgur.com/GIXcM8A.jpg",
							thr_img: "https://i.imgur.com/MqHaQUP.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "L4c10y",
							title: "保険の申し込み方",
							category: "生活相談",
							host: "渡辺愛莉",
							date: "11/02/2017",
							price: "¥1500/時",
							img: "https://i.imgur.com/v1JbZ3h.jpg",
							url: "/details/requests/life/L4c10y",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/v1JbZ3h.jpg",
							sec_img: "https://i.imgur.com/FeKfXsD.jpg",
							thr_img: "https://i.imgur.com/mZxKsxg.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "jW1h44",
							title: "引っ越し手伝い募集中",
							category: "交通",
							host: "高橋恵介",
							date: "11/03/2017",
							price: "¥2000/時",
							img: "https://i.imgur.com/wJGbDaM.jpg",
							url: "/details/requests/life/jW1h44",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/wJGbDaM.jpg",
							sec_img: "https://i.imgur.com/AP48h4L.jpg",
							thr_img: "https://i.imgur.com/vpOMwM9.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "T8kf21",
							title: "日本語でお話しませんか？",
							category: "生活相談",
							host: "鈴木美咲",
							date: "11/04/2017",
							price: "¥2500/時",
							img: "https://i.imgur.com/BBBfGcN.jpg",
							url: "/details/requests/life/T8kf21",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/BBBfGcN.jpg",
							sec_img: "https://i.imgur.com/VLRkgd9.jpg",
							thr_img: "https://i.imgur.com/KO2exIV.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
					],
				},
				support: {
					buddies: [
						{
							id: "b1i53i",
							title: "名古屋市内の案内お願いします！",
							category: "その他",
							host: "伊藤杏那",
							date: "11/01/2017",
							price: "¥500/時",
							img: "https://i.imgur.com/anNQR3T.jpg",
							url: "/details/support/buddies/b1i53i",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/anNQR3T.jpg",
							sec_img: "https://i.imgur.com/GIXcM8A.jpg",
							thr_img: "https://i.imgur.com/MqHaQUP.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "L4c10y",
							title: "保険の申し込み方",
							category: "生活相談",
							host: "渡辺愛莉",
							date: "11/02/2017",
							price: "¥1500/時",
							img: "https://i.imgur.com/v1JbZ3h.jpg",
							url: "/details/support/buddies/L4c10y",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/v1JbZ3h.jpg",
							sec_img: "https://i.imgur.com/FeKfXsD.jpg",
							thr_img: "https://i.imgur.com/mZxKsxg.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "jW1h44",
							title: "引っ越し手伝い募集中",
							category: "交通",
							host: "高橋恵介",
							date: "11/03/2017",
							price: "¥2000/時",
							img: "https://i.imgur.com/wJGbDaM.jpg",
							url: "/details/support/buddies/jW1h44",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/wJGbDaM.jpg",
							sec_img: "https://i.imgur.com/AP48h4L.jpg",
							thr_img: "https://i.imgur.com/vpOMwM9.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "T8kf21",
							title: "日本語でお話しませんか？",
							category: "生活相談",
							host: "鈴木美咲",
							date: "11/04/2017",
							price: "¥2500/時",
							img: "https://i.imgur.com/BBBfGcN.jpg",
							url: "/details/support/buddies/T8kf21",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/BBBfGcN.jpg",
							sec_img: "https://i.imgur.com/VLRkgd9.jpg",
							thr_img: "https://i.imgur.com/KO2exIV.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
					],
					events: [
						{
							id: "o2p21n",
							title: "府ば応督ぱ生味おほその!",
							category: "その他",
							host: "佐藤夏希",
							date: "10/31/2017",
							price: "¥900/人",
							img: "https://placeimg.com/300/250/any?t=1509097137288",
							url: "/details/support/events/o2p21n",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102511822",
							sec_img: "",
							thr_img: "",
							time: "2時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "gt2v51",
							title: "府ば応督ぱ生味おほその2!",
							category: "その他",
							host: "田中直樹",
							date: "11/01/2017",
							price: "¥4000/人",
							img: "https://placeimg.com/300/250/any?t=1509097296222",
							url: "/details/support/events/gt2v51",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102723222",
							sec_img: "",
							thr_img: "",
							time: "3時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "i8u1l2",
							title: "Coffee & Code: Let's プログラム!",
							category: "学業",
							host: "松本健三",
							date: "11/02/2017",
							price: "¥1200/人",
							img: "https://placeimg.com/300/250/any?t=1509097251840",
							url: "/details/support/events/i8u1l2",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/tech?t=1509102941505",
							sec_img: "",
							thr_img: "",
							time: "7時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "ilu812",
							title: "ハイクで美しい自然を感動させます。",
							category: "その他",
							host: "木村海斗",
							date: "11/03/2017",
							price: "¥5000/人",
							img: "https://placeimg.com/300/250/any?t=1509097278497",
							url: "/details/support/events/ilu812",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102744365",
							sec_img: "",
							thr_img: "",
							time: "12時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
					],
					life: [
						{
							id: "o2p21n",
							title: "かわいい猫と遊びしましょう!",
							category: "その他",
							host: "佐藤夏希",
							date: "10/31/2017",
							price: "¥1500/人",
							img: "https://placeimg.com/300/250/any?t=1509097137288",
							url: "/details/support/life/o2p21n",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102511822",
							sec_img: "",
							thr_img: "",
							time: "2時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "gt2v51",
							title: "かわいい猫と写真を取りましょう!",
							category: "その他",
							host: "田中直樹",
							date: "11/01/2017",
							price: "¥4000/人",
							img: "https://placeimg.com/300/250/any?t=1509097296222",
							url: "/details/support/life/gt2v51",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102723222",
							sec_img: "",
							thr_img: "",
							time: "3時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "i8u1l2",
							title: "Coffee & Code: Let's プログラム!",
							category: "学業",
							host: "松本健三",
							date: "11/02/2017",
							price: "¥1200/人",
							img: "https://placeimg.com/300/250/any?t=1509097251840",
							url: "/details/support/life/i8u1l2",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/tech?t=1509102941505",
							sec_img: "",
							thr_img: "",
							time: "7時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "ilu812",
							title: "ハイクで美しい自然を感動させます。",
							category: "その他",
							host: "木村海斗",
							date: "11/03/2017",
							price: "¥5000/人",
							img: "https://placeimg.com/300/250/any?t=1509097278497",
							url: "/details/support/life/ilu812",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102744365",
							sec_img: "",
							thr_img: "",
							time: "12時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
					],
				},
				view: {
					navbar: {
						sublogo: "Meet partners, connect, support.",
						about: "About",
						logIn: "Log In",
						logOut: "Log Out",
						signUp: "Sign Up",
					},
					home:  {
						home: "Home",
						recommended: "Recommended",
						filters: "Categories",
						requests: "Featured Requests",
						support: "Featured Support",
						buddies: "Buddies",
						events: "Events",
						life: "Life",
						siteBlurb: "Buddies is a win-win service thats makes a link between local people and overseas people.",
						siteBlurbPic: "https://i.imgur.com/4TCm4Ec.png",
						secureBlurb: "Use with Confidence",
						secureDetailTitle1: "Review Rating",
						secureDetailTitle2: "ID Authentication",
						secureDetailTitle3: "Monitoring",
						secureDetail1: "Quisque nec laoreet metus. Sed commodo feugiat tellus, elementum luctus enim consequat id.",
						secureDetail2: "Quisque nec laoreet metus. Sed commodo feugiat tellus, elementum luctus enim consequat id.",
						secureDetail3: "Quisque nec laoreet metus. Sed commodo feugiat tellus, elementum luctus enim consequat id.",
						more: "More",
					},
					categories: {
						buddies: ["All 'Buddies'","Transportation","City Hall","School","Hospital","Bank/Finance","Child","Hobby","Life Consultation","Cooking","Diet","Beauty/Fashion","Other 'Buddies'"],
						events: ["All 'Events'","Home Party","Izakaya/Bar", "Other 'Events'"],
						life:  ["All 'Life'","Life","Culture","Studies","Money","Child Rearing","Health","Workplace","Sleep","Other 'Life'"],
					},
					places: ["All","Aichi","Akita","Aomori","Chiba","Ehime","Fukui","Fukuoka","Gifu","Gunma",
								"Hiroshima","Hokkaido","Hyogo","Ibaraki","Ishikawa","Iwate","Kagawa","Kagoshima	","Kanagawa",
								"Kochi","Kumamoto","Kyoto","Mie","Miyagi","Miyazaki","Nagano","Nagasaki","Nara","Niigata",
								"大分県","Okayama","Okinawa","Osaka","Saga","Saitama","Shiga","Shimane","Shizuoka","Tochigi",
								"Tokushima","Tokyo","Tottori","Toyama","Wakayama","Yamagata","Yamaguchi","Yamanashi"]
				},
			},
			japanese: {
				requests: {
					buddies: [
						{
							id: "b1i53i",
							title: "名古屋市内の案内お願いします！",
							category: "その他",
							host: "伊藤杏那",
							date: "11/01/2017",
							price: "¥500/時",
							img: "https://i.imgur.com/anNQR3T.jpg",
							url: "/details/requests/buddies/b1i53i",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/anNQR3T.jpg",
							sec_img: "https://i.imgur.com/GIXcM8A.jpg",
							thr_img: "https://i.imgur.com/MqHaQUP.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "L4c10y",
							title: "保険の申し込み方",
							category: "生活相談",
							host: "渡辺愛莉",
							date: "11/02/2017",
							price: "¥1500/時",
							img: "https://i.imgur.com/v1JbZ3h.jpg",
							url: "/details/requests/buddies/L4c10y",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/v1JbZ3h.jpg",
							sec_img: "https://i.imgur.com/FeKfXsD.jpg",
							thr_img: "https://i.imgur.com/mZxKsxg.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "jW1h44",
							title: "引っ越し手伝い募集中",
							category: "交通",
							host: "高橋恵介",
							date: "11/03/2017",
							price: "¥2000/時",
							img: "https://i.imgur.com/wJGbDaM.jpg",
							url: "/details/requests/buddies/jW1h44",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/wJGbDaM.jpg",
							sec_img: "https://i.imgur.com/AP48h4L.jpg",
							thr_img: "https://i.imgur.com/vpOMwM9.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "T8kf21",
							title: "日本語でお話しませんか？",
							category: "生活相談",
							host: "鈴木美咲",
							date: "11/04/2017",
							price: "¥2500/時",
							img: "https://i.imgur.com/BBBfGcN.jpg",
							url: "/details/requests/buddies/T8kf21",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/BBBfGcN.jpg",
							sec_img: "https://i.imgur.com/VLRkgd9.jpg",
							thr_img: "https://i.imgur.com/KO2exIV.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
					],
					events: [
						{
							id: "WqxNig",
							title: "修えラ党容ヌレシ続改ナヌ演事る",
							category: "その他",
							host: "伊藤杏那",
							date: "11/01/2017",
							price: "¥500/時",
							img: "https://i.imgur.com/anNQR3T.jpg",
							url: "/details/requests/events/WqxNig",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/anNQR3T.jpg",
							sec_img: "https://i.imgur.com/GIXcM8A.jpg",
							thr_img: "https://i.imgur.com/MqHaQUP.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "NMibPR",
							title: "確支ぞどゆ修固逆フ緊歳そリば月提",
							category: "生活相談",
							host: "渡辺愛莉",
							date: "11/02/2017",
							price: "¥1500/時",
							img: "https://i.imgur.com/v1JbZ3h.jpg",
							url: "/details/requests/events/NMibPR",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/v1JbZ3h.jpg",
							sec_img: "https://i.imgur.com/FeKfXsD.jpg",
							thr_img: "https://i.imgur.com/mZxKsxg.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "28JyhA",
							title: "ロカタ員雲月オハ界首姿税づトな",
							category: "交通",
							host: "高橋恵介",
							date: "11/03/2017",
							price: "¥2000/時",
							img: "https://i.imgur.com/wJGbDaM.jpg",
							url: "/details/requests/events/28JyhA",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/wJGbDaM.jpg",
							sec_img: "https://i.imgur.com/AP48h4L.jpg",
							thr_img: "https://i.imgur.com/vpOMwM9.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "tV8XxQ",
							title: "誓けぱな平謙情やつ県幕全",
							category: "生活相談",
							host: "鈴木美咲",
							date: "11/04/2017",
							price: "¥2500/時",
							img: "https://i.imgur.com/BBBfGcN.jpg",
							url: "/details/requests/events/tV8XxQ",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/BBBfGcN.jpg",
							sec_img: "https://i.imgur.com/VLRkgd9.jpg",
							thr_img: "https://i.imgur.com/KO2exIV.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
					],
					life: [
						{
							id: "yxthXP",
							title: "仙除うざに山野すめばさ鮮発ウ持患養えぐる！",
							category: "その他",
							host: "伊藤杏那",
							date: "11/01/2017",
							price: "¥5500/時",
							img: "https://i.imgur.com/anNQR3T.jpg",
							url: "/details/requests/life/yxthXP",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/anNQR3T.jpg",
							sec_img: "https://i.imgur.com/GIXcM8A.jpg",
							thr_img: "https://i.imgur.com/MqHaQUP.jpg",
							time: "3時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "hB9i8f",
							title: "このほし指見ク突部ぞ案4世",
							category: "生活相談",
							host: "渡辺愛莉",
							date: "11/02/2017",
							price: "¥6500/時",
							img: "https://i.imgur.com/v1JbZ3h.jpg",
							url: "/details/requests/life/hB9i8f",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/v1JbZ3h.jpg",
							sec_img: "https://i.imgur.com/FeKfXsD.jpg",
							thr_img: "https://i.imgur.com/mZxKsxg.jpg",
							time: "2時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "16KrDG",
							title: "ルカ店図キリソウ労年がお日済た",
							category: "交通",
							host: "高橋恵介",
							date: "11/03/2017",
							price: "¥2300/時",
							img: "https://i.imgur.com/wJGbDaM.jpg",
							url: "/details/requests/life/16KrDG",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/wJGbDaM.jpg",
							sec_img: "https://i.imgur.com/AP48h4L.jpg",
							thr_img: "https://i.imgur.com/vpOMwM9.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
						{
							id: "5tfKY3",
							title: "時にばぶご影色シツ込毎アヌノ任倫？",
							category: "生活相談",
							host: "鈴木美咲",
							date: "11/04/2017",
							price: "¥1400/時",
							img: "https://i.imgur.com/BBBfGcN.jpg",
							url: "/details/requests/life/5tfKY3",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/BBBfGcN.jpg",
							sec_img: "https://i.imgur.com/VLRkgd9.jpg",
							thr_img: "https://i.imgur.com/KO2exIV.jpg",
							time: "3時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							languages: "日本語、中国語、英語",
						},
					],
				},
				support: {
					buddies: [
						{
							id: "bDz153",
							title: "携帯の契約に付き添います",
							category: "Services",
							host: "山田大翔",
							date: "11/01/2017",
							price: "¥2000/人",
							img: "https://i.imgur.com/XsrlVdD.jpg",
							url: "/details/support/buddies/bDz153",
							subtitle: "名古屋市内の大手3社携帯電話会社への契約のお手伝いをします。",
							main_img: "https://i.imgur.com/XsrlVdD.jpg",
							sec_img: "https://i.imgur.com/khqbV6g.jpg",
							thr_img: "https://i.imgur.com/qimhUev.jpg",
							time: "2時間",
							memo: "身分証明書、あればご自分の銀行のキャッシュカードもお持ちください。",
							meeting: "名古屋駅金時計前",
							languages: "日本語、中国語、英語",
							profile: "名古屋市在住の二児の父親です。昭和区で旅館業許可書（簡易宿所）を取得してAirbnbを運営しています。普通自動車免許所持しています。簡単な英語、中国語でのやりとりは可能なので仕事の依頼もどうぞ。",
							event_info: "日本に来たばかりの方々のために、携帯電話契約のお手伝いをします。中国語、英語での通訳ができるので日本語が出来ない方にはおすすめです！価格はお一人ずつに頂く料金となっております。通常2,3名の方をグループでお連れしています。他にも付き添いのリクエストがございましたら、お気軽にご連絡ください！",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I",
						},
						{
							id: "b1d5io3",
							title: "名古屋大学周辺を案内します！",
							category: "Nature/Area",
							host: "中村正博",
							date: "11/02/2017",
							price: "¥3500/人",
							img: "https://i.imgur.com/ydqPRYH.jpg",
							url: "/details/support/buddies/b1d5io3",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/ydqPRYH.jpg",
							sec_img: "https://i.imgur.com/hVOOHHE.jpg",
							thr_img: "https://i.imgur.com/SZ1rBAu.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I",
						},
						{
							id: "Cz5e48",
							title: "自転車の保険を申し込みます",
							category: "Services",
							host: "小林春菜",
							date: "11/03/2017",
							price: "¥1000/人",
							img: "https://i.imgur.com/jznhc6d.jpg",
							url: "/details/support/buddies/Cz5e48",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/jznhc6d.jpg",
							sec_img: "https://i.imgur.com/vy6cKmz.jpg",
							thr_img: "https://i.imgur.com/FMnJMlp.jpg",
							time: "1時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I",
						},
						{
							id: "Ff15p3",
							title: "一緒に日本のレシピーを慣れます",
							category: "Cooking",
							host: "山本大輔",
							date: "11/04/2017",
							price: "¥4000/人",
							img: "https://i.imgur.com/B49UcfC.jpg",
							url: "/details/support/buddies/Ff15p3",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://i.imgur.com/B49UcfC.jpg",
							sec_img: "https://i.imgur.com/npdizQm.jpg",
							thr_img: "https://i.imgur.com/jGz6o3d.jpg",
							time: "5時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I",
						},
					],
					events: [
						{
							id: "o2p21n",
							title: "府ば応督ぱ生味おほその!",
							category: "その他",
							host: "佐藤夏希",
							date: "10/31/2017",
							price: "¥900/人",
							img: "https://placeimg.com/300/250/any?t=1509097137288",
							url: "/details/support/events/o2p21n",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102511822",
							sec_img: "",
							thr_img: "",
							time: "2時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "gt2v51",
							title: "府ば応督ぱ生味おほその2!",
							category: "その他",
							host: "田中直樹",
							date: "11/01/2017",
							price: "¥4000/人",
							img: "https://placeimg.com/300/250/any?t=1509097296222",
							url: "/details/support/events/gt2v51",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102723222",
							sec_img: "",
							thr_img: "",
							time: "3時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "i8u1l2",
							title: "Coffee & Code: Let's プログラム!",
							category: "学業",
							host: "松本健三",
							date: "11/02/2017",
							price: "¥1200/人",
							img: "https://placeimg.com/300/250/any?t=1509097251840",
							url: "/details/support/events/i8u1l2",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/tech?t=1509102941505",
							sec_img: "",
							thr_img: "",
							time: "7時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "ilu812",
							title: "ハイクで美しい自然を感動させます。",
							category: "その他",
							host: "木村海斗",
							date: "11/03/2017",
							price: "¥5000/人",
							img: "https://placeimg.com/300/250/any?t=1509097278497",
							url: "/details/support/events/ilu812",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102744365",
							sec_img: "",
							thr_img: "",
							time: "12時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
					],
					life: [
						{
							id: "5Au4hN",
							title: "かわいい猫と遊びしましょう!",
							category: "その他",
							host: "佐藤夏希",
							date: "10/31/2017",
							price: "¥1500/人",
							img: "https://placeimg.com/300/250/any?t=1509097137288",
							url: "/details/support/life/5Au4hN",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102511822",
							sec_img: "",
							thr_img: "",
							time: "2時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "CFZ0ec",
							title: "かわいい猫と写真を取りましょう!",
							category: "その他",
							host: "田中直樹",
							date: "11/01/2017",
							price: "¥4000/人",
							img: "https://placeimg.com/300/250/any?t=1509097296222",
							url: "/details/support/life/CFZ0ec",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102723222",
							sec_img: "",
							thr_img: "",
							time: "3時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "WRWiik",
							title: "Coffee & Code: Let's プログラム!",
							category: "学業",
							host: "松本健三",
							date: "11/02/2017",
							price: "¥1200/人",
							img: "https://placeimg.com/300/250/any?t=1509097251840",
							url: "/details/support/life/WRWiik",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/tech?t=1509102941505",
							sec_img: "",
							thr_img: "",
							time: "7時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
						{
							id: "vxP7Yv",
							title: "ハイクで美しい自然を感動させます。",
							category: "その他",
							host: "木村海斗",
							date: "11/03/2017",
							price: "¥5000/人",
							img: "https://placeimg.com/300/250/any?t=1509097278497",
							url: "/details/support/life/vxP7Yv",
							subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず!",
							main_img: "https://placeimg.com/1000/1000/any?t=1509102744365",
							sec_img: "",
							thr_img: "",
							time: "12時間",
							memo: "持ち物、食べ物、飲み物",
							meeting: "搭監48購伐唄づめ。",
							languages: "日本語、中国語、英語",
							profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
							event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
							map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
						},
					],
				},
				view: {
					navbar: {
						sublogo: "仲間と出会い、つながる、支え合う",
						about: "Buddiesについて",
						logIn: "ログイン",
						logOut: "ログアウト",
						signUp: "新規登録",
					},
					home:  {
						home: "ホーム",
						recommended: "おすすめ",
						filters: "カテゴリー",
						requests: "みんなのリクエスト",
						support: "みんなのサポート",
						buddies: "Buddies",
						events: "イベント",
						life: "生活",
						siteBlurb: "Buddiesは海外から来た人と現地のつなげwin-winを作るサービスです。",
						siteBlurbPic: "https://i.imgur.com/4TCm4Ec.png",
						secureBlurb: "安心してご利用していただくための取り組み",
						secureDetailTitle1: "レビュー評価",
						secureDetailTitle2: "ID認証",
						secureDetailTitle3: "パトロール",
						secureDetail1: "サービスが完了した後、利用者と提供者双方がお互いにレビューする制度を設けています。5 段階評価制度を導入しております。評価とコメントがプロフィールに表示されるため、サービスを利用する前にそれぞれの評価を確認できます。",
						secureDetail2: "本人確認書（パスポート、運転免許証など）を提出していただき、ID認証をさせていただいています。任意で電話確認も実施しており、認証マークをつけております。ユーザーの信頼度を確認できるようになっております。",
						secureDetail3: "ユーザー同士での取引内容、メッセージ、サービスに不適切なものがないかBuddies事務局のカスタマーサポートがパトロールを行っております。万が一、トラブルや不適切な取引があった場合は、こちらで適当な処置をさせていただいております。",
						more: "もっと"
					},
					categories: {
						buddies: ["すべて 'Buddies'","交通","市役所","学校","病院","銀行・金融","子ども","趣味","生活相談","料理","食事","美容・ファッション","その他 'Buddies'"],
						events: ["すべてエベント","ホームパーティ","居酒屋・バー","その他エベント"],
						life:  ["すべて生活","生活","文化","学業","お金","子育て","健康","職場","睡眠","その他生活"],
					},
					places: ["すべて","愛知県","秋田県","青森県","千葉県","愛媛県","福井県","福岡県","岐阜県","群馬県",
								"広島県","北海道","兵庫県	","茨城県	","石川県	","岩手県	","香川県","鹿児島県	","神奈川県",
								"高知県","熊本県","京都府","三重県","宮城県","宮崎県","長野県","長崎県","奈良県","新潟県",
								"大分県","岡山県","沖縄県","大阪府","佐賀県","埼玉県","滋賀県","島根県","静岡県","栃木県",
								"徳島県","東京都","鳥取県","富山県","和歌山県","山形県","山口県	","山梨県",]
				},
			},
		}
		/*this.data = {
			buddies_data: [
				{
					id: "bDz153",
					title: "携帯の契約に付き添います",
					category: "Services",
					host: "山田大翔",
					date: "11/01/2017",
					price: "¥2000/人",
					img: "https://i.imgur.com/XsrlVdD.jpg",
					url: "/details/buddies/bDz153",
					subtitle: "名古屋市内の大手3社携帯電話会社への契約のお手伝いをします。",
					main_img: "https://i.imgur.com/XsrlVdD.jpg",
					sec_img: "https://i.imgur.com/khqbV6g.jpg",
					thr_img: "https://i.imgur.com/qimhUev.jpg",
					time: "2時間",
					memo: "身分証明書、あればご自分の銀行のキャッシュカードもお持ちください。",
					meeting: "名古屋駅金時計前",
					languages: "日本語、中国語、英語",
					profile: "名古屋市在住の二児の父親です。昭和区で旅館業許可書（簡易宿所）を取得してAirbnbを運営しています。普通自動車免許所持しています。簡単な英語、中国語でのやりとりは可能なので仕事の依頼もどうぞ。",
					event_info: "日本に来たばかりの方々のために、携帯電話契約のお手伝いをします。中国語、英語での通訳ができるので日本語が出来ない方にはおすすめです！価格はお一人ずつに頂く料金となっております。通常2,3名の方をグループでお連れしています。他にも付き添いのリクエストがございましたら、お気軽にご連絡ください！",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I",
				},
				{
					id: "b1d5io3",
					title: "名古屋大学周辺を案内します！",
					category: "Nature/Area",
					host: "中村正博",
					date: "11/02/2017",
					price: "¥3500/人",
					img: "https://i.imgur.com/ydqPRYH.jpg",
					url: "/details/buddies/b1d5io3",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://i.imgur.com/ydqPRYH.jpg",
					sec_img: "https://i.imgur.com/hVOOHHE.jpg",
					thr_img: "https://i.imgur.com/SZ1rBAu.jpg",
					time: "1時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I",
				},
				{
					id: "Cz5e48",
					title: "自転車の保険を申し込みます",
					category: "Services",
					host: "小林春菜",
					date: "11/03/2017",
					price: "¥1000/人",
					img: "https://i.imgur.com/jznhc6d.jpg",
					url: "/details/buddies/Cz5e48",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://i.imgur.com/jznhc6d.jpg",
					sec_img: "https://i.imgur.com/vy6cKmz.jpg",
					thr_img: "https://i.imgur.com/FMnJMlp.jpg",
					time: "1時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I",
				},
				{
					id: "Ff15p3",
					title: "一緒に日本のレシピーを慣れます",
					category: "Cooking",
					host: "山本大輔",
					date: "11/04/2017",
					price: "¥4000/人",
					img: "https://i.imgur.com/B49UcfC.jpg",
					url: "/details/buddies/Ff15p3",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://i.imgur.com/B49UcfC.jpg",
					sec_img: "https://i.imgur.com/npdizQm.jpg",
					thr_img: "https://i.imgur.com/jGz6o3d.jpg",
					time: "5時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I",
				},
			],
			requests_data: [
				{
					id: "b1i53i",
					title: "名古屋市内の案内お願いします！",
					category: "Services",
					host: "伊藤杏那",
					date: "11/01/2017",
					price: "¥500/時",
					img: "https://i.imgur.com/anNQR3T.jpg",
					url: "/details/requests/b1i53i",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://i.imgur.com/anNQR3T.jpg",
					sec_img: "https://i.imgur.com/GIXcM8A.jpg",
					thr_img: "https://i.imgur.com/MqHaQUP.jpg",
					time: "5時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					languages: "日本語、中国語、英語",
				},
				{
					id: "L4c10y",
					title: "保険の申し込み方",
					category: "Nature/Area",
					host: "渡辺愛莉",
					date: "11/02/2017",
					price: "¥1500/時",
					img: "https://i.imgur.com/v1JbZ3h.jpg",
					url: "/details/requests/L4c10y",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://i.imgur.com/v1JbZ3h.jpg",
					sec_img: "https://i.imgur.com/FeKfXsD.jpg",
					thr_img: "https://i.imgur.com/mZxKsxg.jpg",
					time: "1時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					languages: "日本語、中国語、英語",
				},
				{
					id: "jW1h44",
					title: "引っ越し手伝い募集中",
					category: "Services",
					host: "高橋恵介",
					date: "11/03/2017",
					price: "¥2000/時",
					img: "https://i.imgur.com/wJGbDaM.jpg",
					url: "/details/requests/jW1h44",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://i.imgur.com/wJGbDaM.jpg",
					sec_img: "https://i.imgur.com/AP48h4L.jpg",
					thr_img: "https://i.imgur.com/vpOMwM9.jpg",
					time: "1時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					languages: "日本語、中国語、英語",
				},
				{
					id: "T8kf21",
					title: "日本語でお話しませんか？",
					category: "Translation",
					host: "鈴木美咲",
					date: "11/04/2017",
					price: "¥2500/時",
					img: "https://i.imgur.com/BBBfGcN.jpg",
					url: "/details/requests/T8kf21",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://i.imgur.com/BBBfGcN.jpg",
					sec_img: "https://i.imgur.com/VLRkgd9.jpg",
					thr_img: "https://i.imgur.com/KO2exIV.jpg",
					time: "5時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					languages: "日本語、中国語、英語",
				},
			],
			event_data: [
				{
					id: "o2p21n",
					title: "かわいい猫と遊びしましょう！",
					category: "Animals",
					host: "佐藤夏希",
					date: "10/31/2017",
					price: "¥1500/人",
					img: "https://placeimg.com/300/250/any?t=1509097137288",
					url: "/details/events/o2p21n",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://placeimg.com/1000/1000/any?t=1509102511822",
					sec_img: "",
					thr_img: "",
					time: "2時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
				},
				{
					id: "gt2v51",
					title: "かわいい猫と写真を取りましょう！",
					category: "Photography",
					host: "田中直樹",
					date: "11/01/2017",
					price: "¥4000/人",
					img: "https://placeimg.com/300/250/any?t=1509097296222",
					url: "/details/events/gt2v51",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://placeimg.com/1000/1000/any?t=1509102723222",
					sec_img: "",
					thr_img: "",
					time: "3時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
				},
				{
					id: "i8u1l2",
					title: "Coffee & Code: Let's プログラム！",
					category: "Technology",
					host: "松本健三",
					date: "11/02/2017",
					price: "¥1200/人",
					img: "https://placeimg.com/300/250/any?t=1509097251840",
					url: "/details/events/i8u1l2",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://placeimg.com/1000/1000/tech?t=1509102941505",
					sec_img: "",
					thr_img: "",
					time: "7時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
				},
				{
					id: "ilu812",
					title: "ハイクで美しい自然を感動させます。",
					category: "Sports",
					host: "木村海斗",
					date: "11/03/2017",
					price: "¥5000/人",
					img: "https://placeimg.com/300/250/any?t=1509097278497",
					url: "/details/events/ilu812",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://placeimg.com/1000/1000/any?t=1509102744365",
					sec_img: "",
					thr_img: "",
					time: "12時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
				},
			],
			life_data: [
				{
					id: "o2p21n",
					title: "かわいい猫と遊びしましょう！",
					category: "Animals",
					host: "佐藤夏希",
					date: "10/31/2017",
					price: "¥1500/人",
					img: "https://placeimg.com/300/250/any?t=1509097137288",
					url: "/details/events/o2p21n",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://placeimg.com/1000/1000/any?t=1509102511822",
					sec_img: "",
					thr_img: "",
					time: "2時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
				},
				{
					id: "gt2v51",
					title: "かわいい猫と写真を取りましょう！",
					category: "Photography",
					host: "田中直樹",
					date: "11/01/2017",
					price: "¥4000/人",
					img: "https://placeimg.com/300/250/any?t=1509097296222",
					url: "/details/events/gt2v51",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://placeimg.com/1000/1000/any?t=1509102723222",
					sec_img: "",
					thr_img: "",
					time: "3時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
				},
				{
					id: "i8u1l2",
					title: "Coffee & Code: Let's プログラム！",
					category: "Technology",
					host: "松本健三",
					date: "11/02/2017",
					price: "¥1200/人",
					img: "https://placeimg.com/300/250/any?t=1509097251840",
					url: "/details/events/i8u1l2",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://placeimg.com/1000/1000/tech?t=1509102941505",
					sec_img: "",
					thr_img: "",
					time: "7時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
				},
				{
					id: "ilu812",
					title: "ハイクで美しい自然を感動させます。",
					category: "Sports",
					host: "木村海斗",
					date: "11/03/2017",
					price: "¥5000/人",
					img: "https://placeimg.com/300/250/any?t=1509097278497",
					url: "/details/events/ilu812",
					subtitle: "川へフで初険しごち録性ヲルオ教代初違ヲサソヘ属額サエナウ髪器ず！",
					main_img: "https://placeimg.com/1000/1000/any?t=1509102744365",
					sec_img: "",
					thr_img: "",
					time: "12時間",
					memo: "持ち物、食べ物、飲み物",
					meeting: "搭監48購伐唄づめ。",
					languages: "日本語、中国語、英語",
					profile: "府ば応督ぱ生味おほその面事6針ツトロシ支話検ニシ慢生セホニ門現処75句搭監48購伐唄づめ。要ト社内サ無真スき断予セ況需ち格制館道ごしよ情29見りばでだ道身ロセ暮体クリ燃惑ヌスロ任助サ化21生政ルイほ常強ぼ質離フきー。",
					event_info: "心能モホ合選ヤ不山づ西級ハケロ類野ミユ碁際ふイ中属76平ヲツヨオ芸7恩掲くばゅ水拓丸強査断ひど。点あけ作善だにまレ欺半ミモ過収ムオ開介テア島治氏れをりイ代題らっだル芸15可げ合万テタケ著生ぞうフ可秋登ょ職律泊祥クしと。",
					map_url: "https://www.google.com/maps/embed/v1/view?zoom=17&center=35.1699%2C136.9373&key=AIzaSyBASTkNgIJQFwUkpuGJC9XK_iy5cRGA4_I"
				},
			]
		}*/
	}
	retrieveLanguageView(language) {
		return this.data[language].view
	}
	retrieveData(language) {
		return this.data[language]
	}
	retrieveDetailData(language, section, page, id){
		let data = this.data[language][section][page]
		for(var x = 0; x < data.length; x++) {
			if(data[x].id === id) {
				return data[x]
			}
		}
	}
}

const pageData = new store()
export default pageData